package fr.uge.greed;

public enum Trames {
	DEMANDECO,	//0
	ACCEPTCO,	//1
	DEMANDERECO, //2
	INTENTIONDECO, //3
	CONFIRMATIONCHANGEMENTCO, //4
	SUPPRESSION, //5
	FIRSTROOT, //6
	FIRSTLEAF, //7
	FULLTREE,  //8
	NEWLEAF,   //9
	PINGENVOI,//10
	PINGREP,   //11
	DONNEEATRAITER,//12
	DONNEEDECO,//13
	DONNEETRAITEES//14
	
}
